export const tinyPlugins = [
    'advlist',
    'anchor',
    'autolink',
    'image',
    'link',
    'lists',
    'searchreplace',
    'code',
    'accordion',
    'preview',
    'importcss',
    'autosave',
    'save',
    'fullscreen',
    'media',
    'codesample',
    // 'table',
    'charmap',
    'pagebreak',
    'nonbreaking',
    'insertdatetime',
    'wordcount',
    'help',
    'quickbars',
    'emoticons',
];
