export const HEADER_HEIGHT_MB = '64';

export const HEADER_HEIGHT_PC = '80';

export const CARTS_KEY = 'carts';

export const STORAGE_KEY = {
    COOKIE_SETTING: 'COOKIE_SETTING',
    APP_INSTALLED: 'APP_INSTALLED',
    CARTS: 'CARTS'
};

export const TIME_FORMAT = 'HH:mm MMM DD,YYYY';
export const DATE_FORMAT = 'DD MMM, YYYY';

export const TEXT_ANIMATION_DELAY = 0.02;

export const emailRegExp =
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export const partnerOptions = [
    {
        label: 'Wholesalers',
        value: 'Wholesalers',
    },
    {
        label: 'Retailers',
        value: 'Retailers',
    },
    {
        label: 'Festivals',
        value: 'Festivals',
    },
    {
        label: 'Activations',
        value: 'Activations',
    },
    {
        label: 'Shows',
        value: 'Shows',
    },
    {
        label: 'Press',
        value: 'Press',
    },
    {
        label: 'Custom items',
        value: 'Custom items',
    },
    {
        label: 'Something else',
        value: 'Something else',
    },
];

export const headerItem = [
    {
        title: 'Fans',
        keyActive: 'Fans',
        href: '/fans',
    },
    {
        title: 'Creators',
        keyActive: 'Creators',
        href: '/creators',
    },
];

export const fanHeaderItem = [
    {
        title: 'Why KNKY?',
        keyActive: 'why',
        href: '#Introduction',
    },
    {
        title: 'Features',
        keyActive: 'Features',
        href: '#Features',
    },
    {
        title: 'Prime',
        keyActive: 'Creators',
        href: '#Prime',
    },
    // {
    //     title: 'MatchMaker',
    //     keyActive: 'Creators',
    //     href: '#MatchMaker',
    // },
    {
        title: 'Connections',
        keyActive: 'Connections',
        href: '#Connections',
    },
    {
        title: 'FAQs',
        keyActive: 'Creators',
        href: '#FAQs',
    }
];

export const creatorHeaderItem = [
    {
        title: 'Why KNKY?',
        keyActive: 'Why',
        href: '#WhyIsKnky',
    },
    {
        title: 'Earning Est',
        keyActive: 'Earning',
        href: '#Earning',
    },
    {
        title: 'Features',
        keyActive: 'Features',
        href: '#Features',
    },
    {
        title: 'ProCreator',
        keyActive: 'ProCreator',
        href: '#ProCreator',
    },
    {
        title: 'FAQs',
        keyActive: 'FAQs',
        href: '#FAQs',
    }
];

export interface ICategoryParent {
    key: number
    title: string
}
export const categoryParents: ICategoryParent[] = [
    {
        key: 1,
        title: 'Beverages',
    },
    {
        key: 2,
        title: 'Accessoires',
    },
    {
        key: 3,
        title: 'Merch',
    },
];

export interface DialCode {
    name: string;
    phone: string;
    isoCode: string;
    flag: string
}
export const dialCodes: DialCode[] = [
    {
        name: 'Afghanistan',
        phone: '+93',
        isoCode: 'AF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/af.svg',
    },
    {
        name: 'Aland Islands',
        phone: '+358 18',
        isoCode: 'AX',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ax.svg',
    },
    {
        name: 'Albania',
        phone: '+355',
        isoCode: 'AL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/al.svg',
    },
    {
        name: 'Algeria',
        phone: '+213',
        isoCode: 'DZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/dz.svg',
    },
    {
        name: 'American Samoa',
        phone: '+1684',
        isoCode: 'AS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/as.svg',
    },
    {
        name: 'Andorra',
        phone: '+376',
        isoCode: 'AD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ad.svg',
    },
    {
        name: 'Angola',
        phone: '+244',
        isoCode: 'AO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ao.svg',
    },
    {
        name: 'Anguilla',
        phone: '+1264',
        isoCode: 'AI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ai.svg',
    },
    {
        name: 'Antarctica',
        phone: '+672',
        isoCode: 'AQ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/aq.svg',
    },
    {
        name: 'Antigua and Barbuda',
        phone: '+1268',
        isoCode: 'AG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ag.svg',
    },
    {
        name: 'Argentina',
        phone: '+54',
        isoCode: 'AR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ar.svg',
    },
    {
        name: 'Armenia',
        phone: '+374',
        isoCode: 'AM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/am.svg',
    },
    {
        name: 'Aruba',
        phone: '+297',
        isoCode: 'AW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/aw.svg',
    },
    {
        name: 'Ascension Island',
        phone: '+247',
        isoCode: 'AC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ac.svg',
    },
    {
        name: 'Australia',
        phone: '+61',
        isoCode: 'AU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/au.svg',
    },
    {
        name: 'Austria',
        phone: '+43',
        isoCode: 'AT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/at.svg',
    },
    {
        name: 'Azerbaijan',
        phone: '+994',
        isoCode: 'AZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/az.svg',
    },
    {
        name: 'Bahamas',
        phone: '+1242',
        isoCode: 'BS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bs.svg',
    },
    {
        name: 'Bahrain',
        phone: '+973',
        isoCode: 'BH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bh.svg',
    },
    {
        name: 'Bangladesh',
        phone: '+880',
        isoCode: 'BD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bd.svg',
    },
    {
        name: 'Barbados',
        phone: '+1246',
        isoCode: 'BB',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bb.svg',
    },
    {
        name: 'Belarus',
        phone: '+375',
        isoCode: 'BY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/by.svg',
    },
    {
        name: 'Belgium',
        phone: '+32',
        isoCode: 'BE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/be.svg',
    },
    {
        name: 'Belize',
        phone: '+501',
        isoCode: 'BZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bz.svg',
    },
    {
        name: 'Benin',
        phone: '+229',
        isoCode: 'BJ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bj.svg',
    },
    {
        name: 'Bermuda',
        phone: '+1441',
        isoCode: 'BM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bm.svg',
    },
    {
        name: 'Bhutan',
        phone: '+975',
        isoCode: 'BT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bt.svg',
    },
    {
        name: 'Bolivia',
        phone: '+591',
        isoCode: 'BO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bo.svg',
    },
    {
        name: 'Bosnia and Herzegovina',
        phone: '+387',
        isoCode: 'BA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ba.svg',
    },
    {
        name: 'Botswana',
        phone: '+267',
        isoCode: 'BW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bw.svg',
    },
    {
        name: 'Brazil',
        phone: '+55',
        isoCode: 'BR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/br.svg',
    },
    {
        name: 'British Indian Ocean Territory',
        phone: '+246',
        isoCode: 'IO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/io.svg',
    },
    {
        name: 'Brunei Darussalam',
        phone: '+673',
        isoCode: 'BN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bn.svg',
    },
    {
        name: 'Bulgaria',
        phone: '+359',
        isoCode: 'BG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bg.svg',
    },
    {
        name: 'Burkina Faso',
        phone: '+226',
        isoCode: 'BF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bf.svg',
    },
    {
        name: 'Burundi',
        phone: '+257',
        isoCode: 'BI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/bi.svg',
    },
    {
        name: 'Cambodia',
        phone: '+855',
        isoCode: 'KH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kh.svg',
    },
    {
        name: 'Cameroon',
        phone: '+237',
        isoCode: 'CM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cm.svg',
    },
    {
        name: 'Canada',
        phone: '+1',
        isoCode: 'CA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ca.svg',
    },
    {
        name: 'Cape Verde',
        phone: '+238',
        isoCode: 'CV',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cv.svg',
    },
    {
        name: 'Cayman Islands',
        phone: '+1345',
        isoCode: 'KY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ky.svg',
    },
    {
        name: 'Central African Republic',
        phone: '+236',
        isoCode: 'CF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cf.svg',
    },
    {
        name: 'Chad',
        phone: '+235',
        isoCode: 'TD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/td.svg',
    },
    {
        name: 'Chile',
        phone: '+56',
        isoCode: 'CL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cl.svg',
    },
    {
        name: 'China',
        phone: '+86',
        isoCode: 'CN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cn.svg',
    },
    {
        name: 'Cocos (Keeling) Islands',
        phone: '++61 891',
        isoCode: 'CC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cc.svg',
    },
    {
        name: 'Colombia',
        phone: '+57',
        isoCode: 'CO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/co.svg',
    },
    {
        name: 'Comoros',
        phone: '+269',
        isoCode: 'KM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/km.svg',
    },
    {
        name: 'Congo',
        phone: '+242',
        isoCode: 'CG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cg.svg',
    },
    {
        name: 'Cook Islands',
        phone: '+682',
        isoCode: 'CK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ck.svg',
    },
    {
        name: 'Costa Rica',
        phone: '+506',
        isoCode: 'CR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cr.svg',
    },
    {
        name: 'Croatia',
        phone: '+385',
        isoCode: 'HR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/hr.svg',
    },
    {
        name: 'Cuba',
        phone: '+53',
        isoCode: 'CU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cu.svg',
    },
    {
        name: 'Cyprus',
        phone: '+357',
        isoCode: 'CY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cy.svg',
    },
    {
        name: 'Czech Republic',
        phone: '+420',
        isoCode: 'CZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cz.svg',
    },
    {
        name: 'Democratic Republic of the Congo',
        phone: '+243',
        isoCode: 'CD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/cd.svg',
    },
    {
        name: 'Denmark',
        phone: '+45',
        isoCode: 'DK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/dk.svg',
    },
    {
        name: 'Djibouti',
        phone: '+253',
        isoCode: 'DJ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/dj.svg',
    },
    {
        name: 'Dominica',
        phone: '+1767',
        isoCode: 'DM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/dm.svg',
    },
    {
        name: 'Dominican Republic',
        phone: '+1849',
        isoCode: 'DO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/do.svg',
    },
    {
        name: 'Ecuador',
        phone: '+593',
        isoCode: 'EC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ec.svg',
    },
    {
        name: 'Egypt',
        phone: '+20',
        isoCode: 'EG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/eg.svg',
    },
    {
        name: 'El Salvador',
        phone: '+503',
        isoCode: 'SV',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sv.svg',
    },
    {
        name: 'Equatorial Guinea',
        phone: '+240',
        isoCode: 'GQ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gq.svg',
    },
    {
        name: 'Eritrea',
        phone: '+291',
        isoCode: 'ER',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/er.svg',
    },
    {
        name: 'Estonia',
        phone: '+372',
        isoCode: 'EE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ee.svg',
    },
    {
        name: 'Eswatini',
        phone: '+268',
        isoCode: 'SZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sz.svg',
    },
    {
        name: 'Ethiopia',
        phone: '+251',
        isoCode: 'ET',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/et.svg',
    },
    {
        name: 'Falkland Islands (Malvinas)',
        phone: '+500',
        isoCode: 'FK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fk.svg',
    },
    {
        name: 'Faroe Islands',
        phone: '+298',
        isoCode: 'FO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fo.svg',
    },
    {
        name: 'Fiji',
        phone: '+679',
        isoCode: 'FJ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fj.svg',
    },
    {
        name: 'Finland',
        phone: '+358',
        isoCode: 'FI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fi.svg',
    },
    {
        name: 'France',
        phone: '+33',
        isoCode: 'FR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fr.svg',
    },
    {
        name: 'French Guiana',
        phone: '+594',
        isoCode: 'GF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gf.svg',
    },
    {
        name: 'French Polynesia',
        phone: '+689',
        isoCode: 'PF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pf.svg',
    },
    {
        name: 'Gabon',
        phone: '+241',
        isoCode: 'GA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ga.svg',
    },
    {
        name: 'Gambia',
        phone: '+220',
        isoCode: 'GM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gm.svg',
    },
    {
        name: 'Georgia',
        phone: '+995',
        isoCode: 'GE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ge.svg',
    },
    {
        name: 'Germany',
        phone: '+49',
        isoCode: 'DE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/de.svg',
    },
    {
        name: 'Ghana',
        phone: '+233',
        isoCode: 'GH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gh.svg',
    },
    {
        name: 'Gibraltar',
        phone: '+350',
        isoCode: 'GI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gi.svg',
    },
    {
        name: 'Greece',
        phone: '+30',
        isoCode: 'GR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gr.svg',
    },
    {
        name: 'Greenland',
        phone: '+299',
        isoCode: 'GL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gl.svg',
    },
    {
        name: 'Grenada',
        phone: '+1473',
        isoCode: 'GD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gd.svg',
    },
    {
        name: 'Guadeloupe',
        phone: '+590',
        isoCode: 'GP',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gp.svg',
    },
    {
        name: 'Guam',
        phone: '+1671',
        isoCode: 'GU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gu.svg',
    },
    {
        name: 'Guatemala',
        phone: '+502',
        isoCode: 'GT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gt.svg',
    },
    {
        name: 'Guernsey',
        phone: '+44-1481',
        isoCode: 'GG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gg.svg',
    },
    {
        name: 'Guinea',
        phone: '+224',
        isoCode: 'GN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gn.svg',
    },
    {
        name: 'Guinea-Bissau',
        phone: '+245',
        isoCode: 'GW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gw.svg',
    },
    {
        name: 'Guyana',
        phone: '+592',
        isoCode: 'GY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gy.svg',
    },
    {
        name: 'Haiti',
        phone: '+509',
        isoCode: 'HT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ht.svg',
    },
    {
        name: 'Holy See (Vatican City State)',
        phone: '+379',
        isoCode: 'VA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/va.svg',
    },
    {
        name: 'Honduras',
        phone: '+504',
        isoCode: 'HN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/hn.svg',
    },
    {
        name: 'Hong Kong',
        phone: '+852',
        isoCode: 'HK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/hk.svg',
    },
    {
        name: 'Hungary',
        phone: '+36',
        isoCode: 'HU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/hu.svg',
    },
    {
        name: 'Iceland',
        phone: '+354',
        isoCode: 'IS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/is.svg',
    },
    {
        name: 'India',
        phone: '+91',
        isoCode: 'IN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/in.svg',
    },
    {
        name: 'Indonesia',
        phone: '+62',
        isoCode: 'ID',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/id.svg',
    },
    {
        name: 'Iran',
        phone: '+98',
        isoCode: 'IR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ir.svg',
    },
    {
        name: 'Iraq',
        phone: '+964',
        isoCode: 'IQ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/iq.svg',
    },
    {
        name: 'Ireland',
        phone: '+353',
        isoCode: 'IE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ie.svg',
    },
    {
        name: 'Isle of Man',
        phone: '+44-1624',
        isoCode: 'IM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/im.svg',
    },
    {
        name: 'Israel',
        phone: '+972',
        isoCode: 'IL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/il.svg',
    },
    {
        name: 'Italy',
        phone: '+39',
        isoCode: 'IT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/it.svg',
    },
    {
        name: "Ivory Coast / Cote d'Ivoire",
        phone: '+225',
        isoCode: 'CI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ci.svg',
    },
    {
        name: 'Jamaica',
        phone: '+1876',
        isoCode: 'JM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/jm.svg',
    },
    {
        name: 'Japan',
        phone: '+81',
        isoCode: 'JP',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/jp.svg',
    },
    {
        name: 'Jersey',
        phone: '+44-1534',
        isoCode: 'JE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/je.svg',
    },
    {
        name: 'Jordan',
        phone: '+962',
        isoCode: 'JO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/jo.svg',
    },
    {
        name: 'Kazakhstan',
        phone: '+77',
        isoCode: 'KZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kz.svg',
    },
    {
        name: 'Kenya',
        phone: '+254',
        isoCode: 'KE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ke.svg',
    },
    {
        name: 'Kiribati',
        phone: '+686',
        isoCode: 'KI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ki.svg',
    },
    {
        name: "Korea, Democratic People's Republic of Korea",
        phone: '+850',
        isoCode: 'KP',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kp.svg',
    },
    {
        name: 'Korea, Republic of South Korea',
        phone: '+82',
        isoCode: 'KR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kr.svg',
    },
    {
        name: 'Kosovo',
        phone: '+383',
        isoCode: 'XK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/xk.svg',
    },
    {
        name: 'Kuwait',
        phone: '+965',
        isoCode: 'KW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kw.svg',
    },
    {
        name: 'Kyrgyzstan',
        phone: '+996',
        isoCode: 'KG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kg.svg',
    },
    {
        name: 'Laos',
        phone: '+856',
        isoCode: 'LA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/la.svg',
    },
    {
        name: 'Latvia',
        phone: '+371',
        isoCode: 'LV',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lv.svg',
    },
    {
        name: 'Lebanon',
        phone: '+961',
        isoCode: 'LB',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lb.svg',
    },
    {
        name: 'Lesotho',
        phone: '+266',
        isoCode: 'LS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ls.svg',
    },
    {
        name: 'Liberia',
        phone: '+231',
        isoCode: 'LR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lr.svg',
    },
    {
        name: 'Libya',
        phone: '+218',
        isoCode: 'LY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ly.svg',
    },
    {
        name: 'Liechtenstein',
        phone: '+423',
        isoCode: 'LI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/li.svg',
    },
    {
        name: 'Lithuania',
        phone: '+370',
        isoCode: 'LT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lt.svg',
    },
    {
        name: 'Luxembourg',
        phone: '+352',
        isoCode: 'LU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lu.svg',
    },
    {
        name: 'Macau',
        phone: '+853',
        isoCode: 'MO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mo.svg',
    },
    {
        name: 'Madagascar',
        phone: '+261',
        isoCode: 'MG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mg.svg',
    },
    {
        name: 'Malawi',
        phone: '+265',
        isoCode: 'MW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mw.svg',
    },
    {
        name: 'Malaysia',
        phone: '+60',
        isoCode: 'MY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/my.svg',
    },
    {
        name: 'Maldives',
        phone: '+960',
        isoCode: 'MV',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mv.svg',
    },
    {
        name: 'Mali',
        phone: '+223',
        isoCode: 'ML',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ml.svg',
    },
    {
        name: 'Malta',
        phone: '+356',
        isoCode: 'MT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mt.svg',
    },
    {
        name: 'Marshall Islands',
        phone: '+692',
        isoCode: 'MH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mh.svg',
    },
    {
        name: 'Martinique',
        phone: '+596',
        isoCode: 'MQ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mq.svg',
    },
    {
        name: 'Mauritania',
        phone: '+222',
        isoCode: 'MR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mr.svg',
    },
    {
        name: 'Mauritius',
        phone: '+230',
        isoCode: 'MU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mu.svg',
    },
    {
        name: 'Mayotte',
        phone: '+262',
        isoCode: 'YT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/yt.svg',
    },
    {
        name: 'Mexico',
        phone: '+52',
        isoCode: 'MX',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mx.svg',
    },
    {
        name: 'Micronesia, Federated States of Micronesia',
        phone: '+691',
        isoCode: 'FM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/fm.svg',
    },
    {
        name: 'Moldova',
        phone: '+373',
        isoCode: 'MD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/md.svg',
    },
    {
        name: 'Monaco',
        phone: '+377',
        isoCode: 'MC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mc.svg',
    },
    {
        name: 'Mongolia',
        phone: '+976',
        isoCode: 'MN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mn.svg',
    },
    {
        name: 'Montenegro',
        phone: '+382',
        isoCode: 'ME',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/me.svg',
    },
    {
        name: 'Montserrat',
        phone: '+1664',
        isoCode: 'MS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ms.svg',
    },
    {
        name: 'Morocco',
        phone: '+212',
        isoCode: 'MA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ma.svg',
    },
    {
        name: 'Mozambique',
        phone: '+258',
        isoCode: 'MZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mz.svg',
    },
    {
        name: 'Myanmar',
        phone: '+95',
        isoCode: 'MM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mm.svg',
    },
    {
        name: 'Namibia',
        phone: '+264',
        isoCode: 'NA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/na.svg',
    },
    {
        name: 'Nauru',
        phone: '+674',
        isoCode: 'NR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nr.svg',
    },
    {
        name: 'Nepal',
        phone: '+977',
        isoCode: 'NP',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/np.svg',
    },
    {
        name: 'Netherlands',
        phone: '+31',
        isoCode: 'NL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nl.svg',
    },
    {
        name: 'Netherlands Antilles',
        phone: '+599',
        isoCode: 'AN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/an.svg',
    },
    {
        name: 'New Caledonia',
        phone: '+687',
        isoCode: 'NC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nc.svg',
    },
    {
        name: 'New Zealand',
        phone: '+64',
        isoCode: 'NZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nz.svg',
    },
    {
        name: 'Nicaragua',
        phone: '+505',
        isoCode: 'NI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ni.svg',
    },
    {
        name: 'Niger',
        phone: '+227',
        isoCode: 'NE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ne.svg',
    },
    {
        name: 'Nigeria',
        phone: '+234',
        isoCode: 'NG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ng.svg',
    },
    {
        name: 'Niue',
        phone: '+683',
        isoCode: 'NU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nu.svg',
    },
    {
        name: 'Norfolk Island',
        phone: '+672 3',
        isoCode: 'NF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/nf.svg',
    },
    {
        name: 'North Macedonia',
        phone: '+389',
        isoCode: 'MK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mk.svg',
    },
    {
        name: 'Northern Mariana Islands',
        phone: '+1670',
        isoCode: 'MP',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mp.svg',
    },
    {
        name: 'Norway',
        phone: '+47',
        isoCode: 'NO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/no.svg',
    },
    {
        name: 'Oman',
        phone: '+968',
        isoCode: 'OM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/om.svg',
    },
    {
        name: 'Pakistan',
        phone: '+92',
        isoCode: 'PK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pk.svg',
    },
    {
        name: 'Palau',
        phone: '+680',
        isoCode: 'PW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pw.svg',
    },
    {
        name: 'Palestine',
        phone: '+970',
        isoCode: 'PS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ps.svg',
    },
    {
        name: 'Panama',
        phone: '+507',
        isoCode: 'PA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pa.svg',
    },
    {
        name: 'Papua New Guinea',
        phone: '+675',
        isoCode: 'PG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pg.svg',
    },
    {
        name: 'Paraguay',
        phone: '+595',
        isoCode: 'PY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/py.svg',
    },
    {
        name: 'Peru',
        phone: '+51',
        isoCode: 'PE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pe.svg',
    },
    {
        name: 'Philippines',
        phone: '+63',
        isoCode: 'PH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ph.svg',
    },
    {
        name: 'Pitcairn',
        phone: '+872',
        isoCode: 'PN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pn.svg',
    },
    {
        name: 'Poland',
        phone: '+48',
        isoCode: 'PL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pl.svg',
    },
    {
        name: 'Portugal',
        phone: '+351',
        isoCode: 'PT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pt.svg',
    },
    {
        name: 'Puerto Rico',
        phone: '+1939',
        isoCode: 'PR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pr.svg',
    },
    {
        name: 'Qatar',
        phone: '+974',
        isoCode: 'QA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/qa.svg',
    },
    // {
    //     name: 'Reunion',
    //     phone: '+262',
    //     isoCode: 'RE',
    //     flag: 'https://cdn.kcak11.com/CountryFlags/countries/re.svg',
    // },
    {
        name: 'Romania',
        phone: '+40',
        isoCode: 'RO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ro.svg',
    },
    {
        name: 'Russia',
        phone: '+7',
        isoCode: 'RU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ru.svg',
    },
    {
        name: 'Rwanda',
        phone: '+250',
        isoCode: 'RW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/rw.svg',
    },
    {
        name: 'Saint Kitts and Nevis',
        phone: '+1869',
        isoCode: 'KN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/kn.svg',
    },
    {
        name: 'Saint Lucia',
        phone: '+1758',
        isoCode: 'LC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lc.svg',
    },
    {
        name: 'Saint Martin',
        phone: '+590',
        isoCode: 'MF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/mf.svg',
    },
    {
        name: 'Saint Pierre and Miquelon',
        phone: '+508',
        isoCode: 'PM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/pm.svg',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        phone: '+1784',
        isoCode: 'VC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/vc.svg',
    },
    {
        name: 'Samoa',
        phone: '+685',
        isoCode: 'WS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ws.svg',
    },
    {
        name: 'San Marino',
        phone: '+378',
        isoCode: 'SM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sm.svg',
    },
    {
        name: 'Sao Tome and Principe',
        phone: '+239',
        isoCode: 'ST',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/st.svg',
    },
    {
        name: 'Saudi Arabia',
        phone: '+966',
        isoCode: 'SA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sa.svg',
    },
    {
        name: 'Senegal',
        phone: '+221',
        isoCode: 'SN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sn.svg',
    },
    {
        name: 'Serbia',
        phone: '+381',
        isoCode: 'RS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/rs.svg',
    },
    {
        name: 'Seychelles',
        phone: '+248',
        isoCode: 'SC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sc.svg',
    },
    {
        name: 'Sierra Leone',
        phone: '+232',
        isoCode: 'SL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sl.svg',
    },
    {
        name: 'Singapore',
        phone: '+65',
        isoCode: 'SG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sg.svg',
    },
    {
        name: 'Sint Maarten',
        phone: '+1721',
        isoCode: 'SX',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sx.svg',
    },
    {
        name: 'Slovakia',
        phone: '+421',
        isoCode: 'SK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sk.svg',
    },
    {
        name: 'Slovenia',
        phone: '+386',
        isoCode: 'SI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/si.svg',
    },
    {
        name: 'Solomon Islands',
        phone: '+677',
        isoCode: 'SB',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sb.svg',
    },
    {
        name: 'Somalia',
        phone: '+252',
        isoCode: 'SO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/so.svg',
    },
    {
        name: 'South Africa',
        phone: '+27',
        isoCode: 'ZA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/za.svg',
    },
    {
        name: 'South Georgia and the South Sandwich Islands',
        phone: '+500',
        isoCode: 'GS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gs.svg',
    },
    {
        name: 'South Sudan',
        phone: '+211',
        isoCode: 'SS',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ss.svg',
    },
    {
        name: 'Spain',
        phone: '+34',
        isoCode: 'ES',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/es.svg',
    },
    {
        name: 'Sri Lanka',
        phone: '+94',
        isoCode: 'LK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/lk.svg',
    },
    {
        name: 'Sudan',
        phone: '+249',
        isoCode: 'SD',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sd.svg',
    },
    {
        name: 'Suriname',
        phone: '+597',
        isoCode: 'SR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sr.svg',
    },
    {
        name: 'Svalbard and Jan Mayen',
        phone: '+47',
        isoCode: 'SJ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sj.svg',
    },
    {
        name: 'Sweden',
        phone: '+46',
        isoCode: 'SE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/se.svg',
    },
    {
        name: 'Switzerland',
        phone: '+41',
        isoCode: 'CH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ch.svg',
    },
    {
        name: 'Syrian Arab Republic',
        phone: '+963',
        isoCode: 'SY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/sy.svg',
    },
    {
        name: 'Taiwan',
        phone: '+886',
        isoCode: 'TW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tw.svg',
    },
    {
        name: 'Tajikistan',
        phone: '+992',
        isoCode: 'TJ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tj.svg',
    },
    {
        name: 'Tanzania, United Republic of Tanzania',
        phone: '+255',
        isoCode: 'TZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tz.svg',
    },
    {
        name: 'Thailand',
        phone: '+66',
        isoCode: 'TH',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/th.svg',
    },
    {
        name: 'Timor-Leste',
        phone: '+670',
        isoCode: 'TL',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tl.svg',
    },
    {
        name: 'Togo',
        phone: '+228',
        isoCode: 'TG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tg.svg',
    },
    {
        name: 'Tokelau',
        phone: '+690',
        isoCode: 'TK',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tk.svg',
    },
    {
        name: 'Tonga',
        phone: '+676',
        isoCode: 'TO',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/to.svg',
    },
    {
        name: 'Trinidad and Tobago',
        phone: '+1868',
        isoCode: 'TT',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tt.svg',
    },
    {
        name: 'Tunisia',
        phone: '+216',
        isoCode: 'TN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tn.svg',
    },
    {
        name: 'Turkey',
        phone: '+90',
        isoCode: 'TR',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tr.svg',
    },
    {
        name: 'Turkmenistan',
        phone: '+993',
        isoCode: 'TM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tm.svg',
    },
    {
        name: 'Turks and Caicos Islands',
        phone: '+1649',
        isoCode: 'TC',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tc.svg',
    },
    {
        name: 'Tuvalu',
        phone: '+688',
        isoCode: 'TV',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/tv.svg',
    },
    {
        name: 'Uganda',
        phone: '+256',
        isoCode: 'UG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ug.svg',
    },
    {
        name: 'Ukraine',
        phone: '+380',
        isoCode: 'UA',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ua.svg',
    },
    {
        name: 'United Arab Emirates',
        phone: '+971',
        isoCode: 'AE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ae.svg',
    },
    {
        name: 'The United Kingdom',
        phone: '+44',
        isoCode: 'GB',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/gb.svg',
    },
    {
        name: 'The United States',
        phone: '+1',
        isoCode: 'US',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/us.svg',
    },
    {
        name: 'United States Minor Outlying Islands',
        phone: '+246',
        isoCode: 'UMI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/umi.svg',
    },
    {
        name: 'Uruguay',
        phone: '+598',
        isoCode: 'UY',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/uy.svg',
    },
    {
        name: 'Uzbekistan',
        phone: '+998',
        isoCode: 'UZ',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/uz.svg',
    },
    {
        name: 'Vanuatu',
        phone: '+678',
        isoCode: 'VU',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/vu.svg',
    },
    {
        name: 'Venezuela, Bolivarian Republic of Venezuela',
        phone: '+58',
        isoCode: 'VE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ve.svg',
    },
    {
        name: 'Vietnam',
        phone: '+84',
        isoCode: 'VN',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/vn.svg',
    },
    {
        name: 'Virgin Islands, British',
        phone: '+1284',
        isoCode: 'VG',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/vg.svg',
    },
    {
        name: 'Virgin Islands, U.S.',
        phone: '+1340',
        isoCode: 'VI',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/vi.svg',
    },
    {
        name: 'Wallis and Futuna',
        phone: '+681',
        isoCode: 'WF',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/wf.svg',
    },
    {
        name: 'Yemen',
        phone: '+967',
        isoCode: 'YE',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/ye.svg',
    },
    {
        name: 'Zambia',
        phone: '+260',
        isoCode: 'ZM',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/zm.svg',
    },
    {
        name: 'Zimbabwe',
        phone: '+263',
        isoCode: 'ZW',
        flag: 'https://cdn.kcak11.com/CountryFlags/countries/zw.svg',
    },
];
